"""
AegisNet TinyML Edge Model Trainer & Exporter
Trains on-device anomaly detector and exports C/C++ header for ESP32 deployment.
"""

import os
import json
import numpy as np

def generate_synthetic_environmental_dataset(samples=1000):
    np.random.seed(42)
    # Features: [water_level_cm, delta_water_per_min, temp_c, delta_temp, smoke_ppm, delta_smoke]
    # Normal baseline conditions
    water_base = np.random.normal(30.0, 4.0, samples)
    delta_water = np.random.normal(0.1, 0.2, samples)
    
    temp_base = np.random.normal(28.0, 2.5, samples)
    delta_temp = np.random.normal(0.05, 0.1, samples)
    
    smoke_base = np.random.normal(60.0, 15.0, samples)
    delta_smoke = np.random.normal(0.2, 0.5, samples)

    normal_data = np.column_stack([water_base, delta_water, temp_base, delta_temp, smoke_base, delta_smoke])
    return normal_data

def export_c_header(stats: dict, output_path: str):
    header_content = f"""// AegisNet Edge AI - Statistical Parameters for ESP32
// Auto-generated by train_edge_model.py
#ifndef AEGISNET_EDGE_MODEL_H
#define AEGISNET_EDGE_MODEL_H

struct ModelParams {{
    float water_mean;
    float water_std;
    float water_roc_threshold; // cm/min
    
    float temp_mean;
    float temp_std;
    float temp_roc_threshold;  // degC/min
    
    float smoke_mean;
    float smoke_std;
    float smoke_roc_threshold; // ppm/min
}};

static const struct ModelParams AEGIS_MODEL = {{
    .water_mean = {stats['water_mean']:.2f}f,
    .water_std = {stats['water_std']:.2f}f,
    .water_roc_threshold = {stats['water_roc_threshold']:.2f}f,
    
    .temp_mean = {stats['temp_mean']:.2f}f,
    .temp_std = {stats['temp_std']:.2f}f,
    .temp_roc_threshold = {stats['temp_roc_threshold']:.2f}f,
    
    .smoke_mean = {stats['smoke_mean']:.2f}f,
    .smoke_std = {stats['smoke_std']:.2f}f,
    .smoke_roc_threshold = {stats['smoke_roc_threshold']:.2f}f
}};

// Fast on-device inference returning 0-100 risk score
static inline int calculate_flood_risk(float water_level, float delta_water) {{
    float z_level = (water_level - AEGIS_MODEL.water_mean) / AEGIS_MODEL.water_std;
    float roc_factor = (delta_water / AEGIS_MODEL.water_roc_threshold) * 40.0f;
    float score = (z_level * 15.0f) + roc_factor + 15.0f;
    if (score < 0.0f) score = 0.0f;
    if (score > 100.0f) score = 100.0f;
    return (int)score;
}}

static inline int calculate_fire_risk(float temp, float delta_temp, float smoke, float delta_smoke, bool flame) {{
    if (flame) return 95;
    float temp_roc = (delta_temp / AEGIS_MODEL.temp_roc_threshold) * 35.0f;
    float smoke_roc = (delta_smoke / AEGIS_MODEL.smoke_roc_threshold) * 35.0f;
    float score = temp_roc + smoke_roc + (smoke > 150.0f ? 25.0f : 5.0f);
    if (score < 0.0f) score = 0.0f;
    if (score > 100.0f) score = 100.0f;
    return (int)score;
}}

#endif // AEGISNET_EDGE_MODEL_H
"""
    with open(output_path, "w") as f:
        f.write(header_content)
    print(f"[Model Exporter] Exported C/C++ embedded weights to {output_path}")

def main():
    print("[TinyML] Generating synthetic sensor baseline...")
    data = generate_synthetic_environmental_dataset()
    
    stats = {
        'water_mean': float(np.mean(data[:, 0])),
        'water_std': float(np.std(data[:, 0])),
        'water_roc_threshold': 1.5, # 1.5 cm/min indicates flash surge
        
        'temp_mean': float(np.mean(data[:, 2])),
        'temp_std': float(np.std(data[:, 2])),
        'temp_roc_threshold': 2.0, # 2 degC/min indicates combustion
        
        'smoke_mean': float(np.mean(data[:, 4])),
        'smoke_std': float(np.std(data[:, 4])),
        'smoke_roc_threshold': 15.0 # 15 ppm/min indicates active smoke
    }
    
    os.makedirs("firmware/include", exist_ok=True)
    header_path = "firmware/include/edge_model_weights.h"
    export_c_header(stats, header_path)
    
    with open("ml-training/model_metadata.json", "w") as f:
        json.dump(stats, f, indent=2)
    print("[TinyML] Model metadata saved to ml-training/model_metadata.json")

if __name__ == "__main__":
    main()
