services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: aegisnet-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  ai-service:
    build:
      context: ../ai-service
      dockerfile: Dockerfile
    container_name: aegisnet-ai-service
    ports:
      - "8000:8000"
    environment:
      - PORT=8000

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: aegisnet-backend
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MQTT_BROKER_URL=mqtt://mosquitto:1883
      - AI_SERVICE_URL=http://ai-service:8000
    depends_on:
      - mosquitto
      - ai-service
