// AegisNet Edge AI - Statistical Parameters for ESP32
// Auto-generated by train_edge_model.py
#ifndef AEGISNET_EDGE_MODEL_H
#define AEGISNET_EDGE_MODEL_H

struct ModelParams {
    float water_mean;
    float water_std;
    float water_roc_threshold; // cm/min
    
    float temp_mean;
    float temp_std;
    float temp_roc_threshold;  // degC/min
    
    float smoke_mean;
    float smoke_std;
    float smoke_roc_threshold; // ppm/min
};

static const struct ModelParams AEGIS_MODEL = {
    .water_mean = 30.08f,
    .water_std = 3.91f,
    .water_roc_threshold = 1.50f,
    
    .temp_mean = 28.01f,
    .temp_std = 2.46f,
    .temp_roc_threshold = 2.00f,
    
    .smoke_mean = 59.26f,
    .smoke_std = 14.88f,
    .smoke_roc_threshold = 15.00f
};

// Fast on-device inference returning 0-100 risk score
static inline int calculate_flood_risk(float water_level, float delta_water) {
    float z_level = (water_level - AEGIS_MODEL.water_mean) / AEGIS_MODEL.water_std;
    float roc_factor = (delta_water / AEGIS_MODEL.water_roc_threshold) * 40.0f;
    float score = (z_level * 15.0f) + roc_factor + 15.0f;
    if (score < 0.0f) score = 0.0f;
    if (score > 100.0f) score = 100.0f;
    return (int)score;
}

static inline int calculate_fire_risk(float temp, float delta_temp, float smoke, float delta_smoke, bool flame) {
    if (flame) return 95;
    float temp_roc = (delta_temp / AEGIS_MODEL.temp_roc_threshold) * 35.0f;
    float smoke_roc = (delta_smoke / AEGIS_MODEL.smoke_roc_threshold) * 35.0f;
    float score = temp_roc + smoke_roc + (smoke > 150.0f ? 25.0f : 5.0f);
    if (score < 0.0f) score = 0.0f;
    if (score > 100.0f) score = 100.0f;
    return (int)score;
}

#endif // AEGISNET_EDGE_MODEL_H
